import { loader } from 'fumadocs-core/source';
// Virtual module generated by fumadocs-mdx; aliased to ./.source/server.ts in
// tsconfig.json, vite.config.ts and next.config.mjs.
import { docs } from 'fumadocs-mdx:collections/server';

/**
 * The docs content tree, loaded from `content/docs`.
 *
 * Collections are declared `async` in source.config.ts, so page bodies are
 * fetched on demand with `page.data.load()` rather than pulled into the
 * Worker bundle up front.
 */
export const source = loader({
  baseUrl: '/docs',
  source: docs.toFumadocsSource(),
});
