name: Release CI

permissions:
  contents: write
  issues: write
  pull-requests: write

on:
  push:
    tags:
      - 'v*.*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  release:
    name: Release
    if: ${{ !contains(github.ref_name, '-') }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Setup environment
        uses: ./.github/actions/setup-env

      - name: Install deps
        run: pnpm install

      - name: Lint
        run: bun run lint

      - name: Workflow
        run: bun run workflow:readme

      - name: Commit changes
        run: |-
          git diff
          git config --global user.name "lobehubbot"
          git config --global user.email "i@lobehub.com"
          git add .
          git commit -m "📝 docs(bot): Auto sync agents & plugin to readme" || exit 0
          git push
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
